version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/azf-devs/front-end-test/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  frontend:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm install
          npm test

workflows:
  my-custom-workflow:
    jobs:
      - frontend